[package]
name = "Generator-SH-KH-DPH"
version = "0.1.0"
edition = "2024"

[dependencies]
time = { version = "0.3", features = ["parsing", "formatting", "macros", "local-offset"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }